/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import backend.ProfileManager;
import backend.User;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mustafa
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    private ProfileManager profileManager;
    private Profile prev;
    private User user;
    
    public EditProfile(User user,Profile prev) {
        initComponents();
        this.profileManager = new ProfileManager(user);
        this.user = user;
        this.prev = prev;
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        changePFP = new javax.swing.JButton();
        changeCVP = new javax.swing.JButton();
        coverPhoto = new javax.swing.JLabel();
        profilePhoto = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        changeBio = new javax.swing.JButton();
        changePassword = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changePFP.setText("Change profile photo");
        changePFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePFPActionPerformed(evt);
            }
        });

        changeCVP.setText("Change cover photo");
        changeCVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCVPActionPerformed(evt);
            }
        });

        coverPhoto.setBackground(new java.awt.Color(153, 153, 153));

        profilePhoto.setBackground(new java.awt.Color(102, 102, 102));

        changeBio.setText("Change bio");
        changeBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBioActionPerformed(evt);
            }
        });

        changePassword.setText("Change password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coverPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changePFP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeBio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeCVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changePFP)
                            .addComponent(changeCVP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeBio)
                            .addComponent(changePassword))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(doneButton)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePFPActionPerformed
        profileManager.updateProfilePhoto(new ImgSelect());
        refresh();
    }//GEN-LAST:event_changePFPActionPerformed

    private void changeBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBioActionPerformed
        String bio = JOptionPane.showInputDialog(this, "Enter bio:", "Change bio", JOptionPane.PLAIN_MESSAGE);
        profileManager.updateBio(bio);
        refresh();
    }//GEN-LAST:event_changeBioActionPerformed

    private void changeCVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCVPActionPerformed
        profileManager.updateCoverPhoto(new ImgSelect());
        refresh();
    }//GEN-LAST:event_changeCVPActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        String oldPassword = JOptionPane.showInputDialog(this, "Enter your password:", "Change password", JOptionPane.PLAIN_MESSAGE); //takes old password to change it
        //hash oldPassword
        String hashedOldPassword = "";
        if(hashedOldPassword.equals(user.getHashedPassword())){ 
            String newPassword = JOptionPane.showInputDialog(this, "Enter your new password:", "Change password", JOptionPane.PLAIN_MESSAGE);
            //hash newPassword
            String hashedNewPassword = "";
            profileManager.changePassword(hashedNewPassword);
        }
        else{
            JOptionPane.showMessageDialog(this, "Incorrect password", "Change password", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_changePasswordActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        prev.refresh();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void refresh(){
        ImageIcon pfp = new ImageIcon(user.getProfilePhotoPath());
        ImageIcon cvp = new ImageIcon(user.getCoverPhotoPath());
        profilePhoto.setIcon(pfp);
        coverPhoto.setIcon(cvp);
        String bio = user.getBio();
        bioLabel.setText(bio);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioLabel;
    private javax.swing.JButton changeBio;
    private javax.swing.JButton changeCVP;
    private javax.swing.JButton changePFP;
    private javax.swing.JButton changePassword;
    private javax.swing.JLabel coverPhoto;
    private javax.swing.JButton doneButton;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel profilePhoto;
    // End of variables declaration//GEN-END:variables
}
