/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.*;
import frontend.Window;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Mustafa
 */
public class GroupGUIPreviewONLYY extends Window {

    /**
     * Creates new form GroupGUI
     */
    
    private Window prevWindow;
    private Group group;
    private UserDatabase userDatabase= UserDatabase.getInstance();
    private PrimaryAdminRole admin;
    
    public void setPrevWindow(Window prev){
        this.prevWindow = prev;
    }
    
    public GroupGUIPreviewONLYY(Group group) {
        initComponents();
        prepare("Group");
        this.group = group;
       // this.user = user;
        
        //hides buttons for members only

        

        
        

        refresh();
        renderPosts(postsPanel);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupPhotoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        postsPanel = new javax.swing.JPanel();
        groupNameLabel = new javax.swing.JLabel();
        groupDescLabel = new javax.swing.JLabel();
        groupCoverLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        groupPhotoLabel.setText("group photo");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout postsPanelLayout = new javax.swing.GroupLayout(postsPanel);
        postsPanel.setLayout(postsPanelLayout);
        postsPanelLayout.setHorizontalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        postsPanelLayout.setVerticalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(postsPanel);

        groupNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        groupNameLabel.setText("group name");

        groupDescLabel.setText("description");

        groupCoverLabel.setText("cover photo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(groupCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(groupCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(groupNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(groupPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
        renderPosts(postsPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    protected void refresh(){
        groupPhotoLabel.setText("");
        if (group.getGroupPhotoPath() != null) {
            ImageIcon groupPhoto = new ImageIcon(group.getGroupPhotoPath());
            int photoWidth = groupPhotoLabel.getWidth();
            int photoHeight = groupPhotoLabel.getHeight();
            Image scaledPFP = groupPhoto.getImage().getScaledInstance( //scale image to fit label in panel
                    photoWidth, photoHeight, Image.SCALE_SMOOTH);
            groupPhotoLabel.setIcon(new ImageIcon(scaledPFP)); //puts the pfp on the label
        }
        
        groupCoverLabel.setText("");
        if (group.getCoverPhotoPath() != null) {
            ImageIcon groupcover = new ImageIcon(group.getCoverPhotoPath());
            int coverWidth = groupCoverLabel.getWidth();
            int coverHeight = groupCoverLabel.getHeight();
            Image scaledCVP = groupcover.getImage().getScaledInstance( //scale image to fit label in panel
                    coverWidth, coverHeight, Image.SCALE_SMOOTH);
            groupCoverLabel.setIcon(new ImageIcon(scaledCVP)); //puts the cover photo on the label
        }

        String description = group.getDescription();
        String name = group.getName();
        groupNameLabel.setText(name);
        groupDescLabel.setText(description);
    }
    
    private void renderPosts(javax.swing.JPanel panel){
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.removeAll();
        if (group.getPosts().isEmpty()) {
            JLabel noPosts = new JLabel("No posts in group yet.", SwingConstants.CENTER);
            noPosts.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
            panel.add(noPosts, BorderLayout.CENTER);
            panel.revalidate();
            panel.repaint();
            return;
        }

        for (Post post : group.idsToPosts(group.getPosts())) {
            
                //creats panel for each post
                JPanel singlePost = new JPanel();
                singlePost.setLayout(new BorderLayout());
                singlePost.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                singlePost.setBackground(Color.WHITE);

                //sets username 
                User poster = userDatabase.getUserById(Integer.valueOf(post.getAuthorid()));
                JLabel usernameLabel = new JLabel(poster.getUsername(), SwingConstants.LEFT);
                usernameLabel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
                singlePost.add(usernameLabel, BorderLayout.NORTH);

                //if theres an image for the post itll get set
                if (post.getImage() != null) {
                    System.out.println("rendering image");
                    ImageIcon postImage = post.getImage();
                    Image scaledImage = postImage.getImage().getScaledInstance(300, 200, Image.SCALE_SMOOTH);
                    JLabel imageLabel = new JLabel(new ImageIcon(scaledImage));
                    imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    singlePost.add(imageLabel, BorderLayout.CENTER);
                }

                //set the description
                if (post.getText() != null) {
                    JLabel descriptionLabel = new JLabel(post.getText());
                    descriptionLabel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
                    //stes position of the description depending if there's an image or not
                    if (post.getImage() == null) {
                        singlePost.add(descriptionLabel, BorderLayout.CENTER);
                    } else {
                        singlePost.add(descriptionLabel, BorderLayout.SOUTH);
                    }
                }
                //adds the single post to the main panel
                panel.add(singlePost);

            
        }
        panel.revalidate();
        panel.repaint();
    }
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(GroupGUIPreviewONLYY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(GroupGUIPreviewONLYY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(GroupGUIPreviewONLYY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(GroupGUIPreviewONLYY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    //    new GroupGUI().setVisible(true);
                    }
                });
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupCoverLabel;
    private javax.swing.JLabel groupDescLabel;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JLabel groupPhotoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel postsPanel;
    // End of variables declaration//GEN-END:variables
}
