/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.ContentDatabase;
import backend.Group;
import backend.GroupDatabase;
import backend.User;
import backend.UserDatabase;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Youss
 */
public class GroupsSearch extends Window {

    /**
     * Creates new form FriendManager
     */
    private Window prevPage;

    public void setPrevPage(Window prevPage) {
        this.prevPage = prevPage;
    }

    public void setEmail(String email) {
        this.exitEmail = email;
    }

    GroupDatabase groupDatabase = GroupDatabase.getInstance();
    ArrayList<Group> allGroups = groupDatabase.getGroupsList();

    private UserDatabase userDatabase = UserDatabase.getInstance();

    private ContentDatabase contentDatabase = new ContentDatabase();

    // private List<User> allUsers;
    private User user;
    Group selectedGroup = null;

    public GroupsSearch(User user, List<User> allUsers) {
        setEmail(user.getEmail());
        initComponents();
        prepare("Search Groups");
        this.user = user;

        this.jScrollPane1.setVisible(true);
        this.SearchOutput.setVisible(true);

        this.SelectedGroup.setVisible(true);
        this.ViewGroupbtn.setVisible(true);
        this.infoPanel.setVisible(false);
        this.searchBar.setVisible(true);
        this.SearchOutput.setListData(new String[0]);
        this.searchBar.setText("");

        this.JoinButton.setVisible(false);
        this.LeaveButton.setVisible(false);
//        this.jScrollPane1.setVisible(false);

        this.SelectedGroup.setVisible(false);
//        this.infoPanel.setVisible(false);
        this.ViewGroupbtn.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profilePic = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        JoinButton = new javax.swing.JButton();
        LeaveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchOutput = new javax.swing.JList<>();
        Back = new javax.swing.JButton();
        SelectedGroup = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        primaryAdmin = new javax.swing.JLabel();
        ViewGroupbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        JoinButton.setText("Join");
        JoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinButtonActionPerformed(evt);
            }
        });

        LeaveButton.setText("Leave");
        LeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveButtonActionPerformed(evt);
            }
        });

        SearchOutput.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SearchOutput.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SearchOutputValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(SearchOutput);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        SelectedGroup.setText("Selected Group: ");

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Info:");

        Description.setText("Description:");

        primaryAdmin.setText("Primary Admin:");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description)
                            .addComponent(primaryAdmin)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primaryAdmin)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ViewGroupbtn.setText("View Group");
        ViewGroupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGroupbtnActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SelectedGroup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewGroupbtn))
                            .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(JoinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(LeaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)))
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JoinButton, LeaveButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JoinButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LeaveButton))
                            .addComponent(jSeparator2))
                        .addGap(300, 300, 300))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectedGroup)
                            .addComponent(ViewGroupbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addComponent(Back)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JoinButton, LeaveButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewGroupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGroupbtnActionPerformed
        // TODO add your handling code here:
//        Profile p = new Profile(selectedGroup, contentDatabase);
//        p.setPrevPage(this);
//        this.setVisible(false);
    }//GEN-LAST:event_ViewGroupbtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        prevPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SearchOutputValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SearchOutputValueChanged
        // TODO add your handling code here:
        String selectedGroupName = SearchOutput.getSelectedValue();

        if (selectedGroupName != null && !selectedGroupName.isEmpty()) {
            // set the search bar text
            searchBar.setText(selectedGroupName);

            Group selectedGroup = null;

            for (Group group : allGroups) {
                if (group.getName().equals(selectedGroupName)) {
                    selectedGroup = group;
                    break;
                }
            }

            if (selectedGroup != null) {
                this.ViewGroupbtn.setVisible(true);
                this.SelectedGroup.setVisible(true);

                SelectedGroup.setText("Selected Group: " + selectedGroup.getName());
                Description.setText("Description: " + selectedGroup.getDescription());
                primaryAdmin.setText("Primary Admin: " + userDatabase.getUserById(selectedGroup.getPrimaryAdmin()).getUsername());

                profilePic.setIcon(new ImageIcon(selectedGroup.getGroupPhotoPath()));

//                String profilePhotoPath = selectedGroup.getGroupPhotoPath();
//                ImageIcon originalIcon = new ImageIcon(profilePhotoPath);
//                Image scaledImage = originalIcon.getImage().getScaledInstance(profilePic.getWidth(), profilePic.getHeight(), Image.SCALE_SMOOTH);
//                profilePic.setIcon(new ImageIcon(scaledImage));
            }

            this.infoPanel.setVisible(true);

            // Check if the selected user is a friend
            if (!selectedGroup.getMembers().contains(user.getUserId())) {
                this.JoinButton.setVisible(true);
                this.LeaveButton.setVisible(false);
            } else {
                this.JoinButton.setVisible(false);
                this.LeaveButton.setVisible(true);
            }

        }
    }//GEN-LAST:event_SearchOutputValueChanged

    private void LeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveButtonActionPerformed
        String selectedGroupName = SearchOutput.getSelectedValue();
        if (selectedGroupName == null || selectedGroupName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a group first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        GroupDatabase groupDatabase = GroupDatabase.getInstance();
        Group selectedGroup = null;
        for (Group group : groupDatabase.getGroupsList()) {
            if (group.getName().equals(selectedGroupName)) {
                selectedGroup = group;
                break;
            }
        }

        if (selectedGroup != null) {
            // Remove the user from the group's members
            if (selectedGroup.getMembers().contains(user.getUserId())) {
                selectedGroup.getMembers().remove(Integer.valueOf(user.getUserId()));
                groupDatabase.saveToFile(); // Save changes to the database
                JOptionPane.showMessageDialog(this, "You have successfully left the group: " + selectedGroup.getName(), "Success", JOptionPane.INFORMATION_MESSAGE);

                // Update button visibility
                this.JoinButton.setVisible(true);
                this.LeaveButton.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "You are not a member of this group.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selected group not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_LeaveButtonActionPerformed

    private void JoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinButtonActionPerformed
        String selectedGroupName = SearchOutput.getSelectedValue();
        if (selectedGroupName == null || selectedGroupName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a group first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // find the selected group
        for (Group group : groupDatabase.getGroupsList()) {
            if (group.getName().equals(selectedGroupName)) {
                selectedGroup = group;
                break;
            }
        }

        if (selectedGroup != null) {
            // Add the user to the group's members
            if (!selectedGroup.getMembers().contains(user.getUserId())) {
                //send request
                selectedGroup.getRequests().add(user.getUserId());
                groupDatabase.saveToFile();

                JOptionPane.showMessageDialog(this, "You sent a request tojoin the group: " + selectedGroup.getName(), "Success", JOptionPane.INFORMATION_MESSAGE);

                // Update button visibility
                this.JoinButton.setVisible(false);
                this.LeaveButton.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "You are already a member of this group.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selected group not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JoinButtonActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        // TODO add your handling code here:
        //this.infoPanel.setVisible(true);
        //this.jScrollPane1.setVisible(true);
        String searchKey = searchBar.getText().trim();
        if (searchKey.isEmpty()) {
            this.SearchOutput.setListData(new String[0]);
            this.JoinButton.setVisible(false);
            this.LeaveButton.setVisible(false);

            return;
        }
        // get all users to be filtered based on the search key
        ArrayList<String> filteredGroups = new ArrayList<>();

        // filteration
        for (Group group : allGroups) {
            if (group.getName().toLowerCase().contains(searchKey.toLowerCase())) {
                filteredGroups.add(group.getName());
            }
        }

        //add filtred users
        this.SearchOutput.setListData(filteredGroups.toArray(new String[0]));

        // if there is one result, you can automatically select it
        if (filteredGroups.size() == 1) {
            searchBar.setText(filteredGroups.get(0));
            selectGroupByName(filteredGroups.get(0), allGroups);

            String selectedGroupName = SearchOutput.getSelectedValue();

            Group selectedGroup = null;

            for (Group group : allGroups) {
                if (group.getName().equals(selectedGroupName)) {
                    selectedGroup = group;
                    break;
                }
            }

            if (selectedGroup != null) {
                this.ViewGroupbtn.setVisible(true);
                this.SelectedGroup.setVisible(true);

                SelectedGroup.setText("Selected Group: " + selectedGroup.getName());
                Description.setText("Description: " + selectedGroup.getDescription());
                primaryAdmin.setText("Primary Admin: " + userDatabase.getUserById(selectedGroup.getPrimaryAdmin()).getUsername());

                profilePic.setIcon(new ImageIcon(selectedGroup.getGroupPhotoPath()));

//            //old profile pic
//            String profilePhotoPath = selectedGroup.getProfilePhotoPath();
//            ImageIcon originalIcon = new ImageIcon(profilePhotoPath);
//            Image scaledImage = originalIcon.getImage().getScaledInstance(profilePic.getWidth(), profilePic.getHeight(), Image.SCALE_SMOOTH);
//            profilePic.setIcon(new ImageIcon(scaledImage));
            }

            // Show buttons based on membership status
            if (!selectedGroup.getMembers().contains(user.getUserId())) {
                this.JoinButton.setVisible(true);
                this.LeaveButton.setVisible(false);
            } else {
                this.JoinButton.setVisible(false);
                this.LeaveButton.setVisible(true);
            }

        }
    }//GEN-LAST:event_searchBarKeyReleased

    private void selectGroupByName(String groupName, ArrayList<Group> allGroups) {
        for (Group group : allGroups) {
            if (group.getName().equals(groupName)) {
                // Simulate selection
                SearchOutput.setSelectedValue(groupName, true);
                break;
            }
        }
    }


    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchBarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Description;
    private javax.swing.JButton JoinButton;
    private javax.swing.JButton LeaveButton;
    private javax.swing.JList<String> SearchOutput;
    private javax.swing.JLabel SelectedGroup;
    private javax.swing.JButton ViewGroupbtn;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel primaryAdmin;
    private javax.swing.JLabel profilePic;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
