/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.*;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author BLU-RAY
 */
public class NotificationsPanel extends javax.swing.JFrame {
    private ArrayList<Notification> Notifications;
    private User user;
    private RequestHandler requestHandler;
    /**
     * Creates new form NotificationsPanel
     */
    public NotificationsPanel(User user, ArrayList<Notification> Notifications,RequestHandler requestHandler) {
        initComponents();
        this.requestHandler = requestHandler;
        this.Notifications = Notifications;
        this.user = user;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        populateNotifications();
        //jPanel1.add();
    }

    private void populateNotifications() {
        jPanel1.removeAll();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        for (Notification notification : Notifications) {
            if (!notification.getReceivers().contains(user.getUserId())) {
                continue; // Skip notifications not intended for this user
            }

            // Determine if the notification is read or unread for this user
            boolean isUnread = !notification.getIsRead().getOrDefault(user.getUserId(), false);

            // Prepare the display text
            String displayText = String.format("[%s] %s%s: %s",
                    notification.getTimestamp(),
                    isUnread ? "NEW NOTIFICATION: " : "",
                    notification.getType(),
                    notification.getText());

            // Panel for each notification
            JPanel notificationPanel = new JPanel();
            notificationPanel.setLayout(new BorderLayout());
            JLabel notificationLabel = new JLabel(displayText);

            // "Mark as Read" button
            JButton markAsReadButton = new JButton("Mark as Read");
            if (!isUnread) {
                markAsReadButton.setEnabled(false); // Disable button if already read
            }

            markAsReadButton.addActionListener(event -> {
                notification.MarkAsRead(user.getUserId()); // Update isRead status
                populateNotifications(); // Refresh notifications
            });

            // Add components to the panel
            notificationPanel.add(notificationLabel, BorderLayout.CENTER);
            notificationPanel.add(markAsReadButton, BorderLayout.EAST);

            // Add the notification panel to the main panel
            jPanel1.add(notificationPanel);
        }

        // Refresh the panel
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
           /* public void run() {
                new NotificationsPanel(new User(),NotificationDatabase.getInstance()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
