/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import backend.*;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Mustafa
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    private ProfileContent profileContent;
    private User user;
    
    public Profile(User user) {
        initComponents();
        this.setVisible(true);
        this.user = user;
        this.profileContent = new ProfileContent(user);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverPhoto = new javax.swing.JLabel();
        profilePhoto = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        editProfile = new javax.swing.JButton();
        friendsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coverPhoto.setBackground(new java.awt.Color(153, 153, 153));

        profilePhoto.setBackground(new java.awt.Color(102, 102, 102));

        editProfile.setText("Edit profile");
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });

        friendsButton.setText("Friends");
        friendsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coverPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editProfile)
                                .addGap(35, 35, 35)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(friendsButton)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editProfile)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(friendsButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed
        new EditProfile(user,this);
        this.setVisible(false);
    }//GEN-LAST:event_editProfileActionPerformed

    private void friendsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friendsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    protected void refresh(){
        ImageIcon pfp = new ImageIcon(user.getProfilePhotoPath()); 
        ImageIcon cvp = new ImageIcon(user.getCoverPhotoPath()); 
        int pfpWidth = profilePhoto.getWidth();
        int pfpHeight = profilePhoto.getHeight();
        Image scaledPFP = pfp.getImage().getScaledInstance( //scale image to fit label in panel
                pfpWidth, pfpHeight, Image.SCALE_SMOOTH);
        profilePhoto.setIcon(new ImageIcon(scaledPFP)); //puts the pfp on the label
        int cvpWidth = coverPhoto.getWidth();
        int cvpHeight = coverPhoto.getHeight();
        Image scaledCVP = cvp.getImage().getScaledInstance( //scale image to fit label in panel
                cvpWidth, cvpHeight, Image.SCALE_SMOOTH);
        coverPhoto.setIcon(new ImageIcon(scaledCVP)); //puts the cover photo on the label
        String bio = user.getBio();
        bioLabel.setText(bio); 
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel coverPhoto;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton friendsButton;
    private javax.swing.JLabel profilePhoto;
    // End of variables declaration//GEN-END:variables
}
